import type { Exercise } from '../db/types'

// 種目マスタ初期データ(要件§7 + ISS-001種目詳細)
// - initialWeightFactor: 初回提案重量 = 体重 × 係数(ダンベル1個あたり・保守的)
// - benchAngleDeg: ベンチ必須種目の推奨角度。器具設定の角度範囲外なら候補から除外される
// - movementPattern: ピクトグラム分類+筋力キャリブレーション(ISS-002)の換算単位
// - formCues / commonMistake: トレ中に片手で読める簡潔さを最優先(各1行以内)
export const INITIAL_EXERCISES: Omit<Exercise, 'id'>[] = [
  // ===== 胸 =====
  {
    name: 'ダンベルベンチプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'horizontal_press',
    emphasis: 'mid',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
    formCues: [
      '肩甲骨を寄せて下げ、胸を張ったまま押す',
      '手首の真下に肘。前腕は常に床と垂直',
      '下ろすときは2秒かけて胸の高さまで',
    ],
    commonMistake: '肩をすくめて押す(肩に効いて胸に入らない)',
  },
  {
    name: 'インクラインダンベルプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'horizontal_press',
    emphasis: 'upper',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 30,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.18,
    isActive: 1,
    note: '胸上部狙い',
    formCues: ['ベンチは30°に設定', '鎖骨の真上に向かって押し上げる', '腰を反りすぎず尻はベンチに着けたまま'],
    commonMistake: '角度が高すぎて肩の種目になる(45°以上はNG)',
  },
  {
    name: 'デクラインダンベルプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'arms'],
    movementType: 'compound',
    movementPattern: 'horizontal_press',
    emphasis: 'lower',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: -15,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
    note: '胸下部狙い',
    formCues: ['ベンチは-15°に設定し脚をしっかり固定', 'みぞおちの真上に押し上げる'],
    commonMistake: '頭に血が上る前に終わる重量設定を(粘りすぎ注意)',
  },
  {
    name: 'ダンベルフライ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'mid',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.1,
    isActive: 1,
    formCues: ['肘は軽く曲げたまま固定して弧を描く', '胸のストレッチを感じる深さまで下ろす', '上げきったとき胸の内側を絞る'],
    commonMistake: '肘が曲がってプレスになる(重すぎのサイン)',
  },
  {
    name: 'インクラインダンベルフライ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'upper',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 30,
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.09,
    isActive: 1,
    formCues: ['ベンチは30°に設定', '鎖骨の延長線上で弧を描く', '重量より胸上部のストレッチ優先'],
    commonMistake: '下ろしすぎて肩前面に負担をかける',
  },
  {
    name: 'プッシュアップ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'horizontal_press',
    emphasis: 'mid',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 10,
    repRangeMax: 20,
    isActive: 1,
    formCues: ['頭からかかとまで一直線をキープ', '手は肩幅よりこぶし1つ外、胸を床に近づける'],
    commonMistake: '腰が落ちる/尻が上がる(体幹が抜けている)',
  },
  {
    name: 'デクラインプッシュアップ',
    searchKeyword: '足上げ腕立て伏せ やり方',
    // 強調はupper(DEC-012 PM裁定): 足上げにより押す角度がインクラインプレス相当になるため。
    // 「デクライン系=lower」ルールはベンチ種目の命名前提で、プッシュアップでは名前と実態が逆転する
    emphasis: 'upper',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'horizontal_press',
    requiredEquipment: ['bodyweight', 'bench'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
    note: '足をベンチに乗せる。胸上部狙い',
    formCues: ['足をベンチに乗せ、体は一直線', '目線はやや前、胸から床に近づく'],
    commonMistake: '首だけ下げて可動域をごまかす',
  },
  // ===== 背中 =====
  {
    name: 'ワンハンドダンベルロウ',
    searchKeyword: 'ワンハンドロウ フォーム',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    movementPattern: 'row',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.28,
    isActive: 1,
    note: '片手・片膝をベンチに置く',
    formCues: ['片手片膝をベンチに置き背中は床と平行', '肘を腰ポケットに向かって引く', '下ろすとき肩甲骨を開いてストレッチ'],
    commonMistake: '体をひねって反動で上げる',
  },
  {
    name: 'ベントオーバーダンベルロウ',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    movementPattern: 'row',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
    formCues: ['股関節から上体を45°前傾、背すじは真っ直ぐ', '両肘を体側に沿って後ろに引く', 'みぞおちとへその間に引き込むイメージ'],
    commonMistake: '背中が丸まる(腰痛リスク。前傾を浅くしてOK)',
  },
  {
    name: 'チェストサポーテッドロウ',
    searchKeyword: 'インクラインベンチ ダンベルロウ フォーム',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    movementPattern: 'row',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 45,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.18,
    isActive: 1,
    note: 'インクラインベンチにうつ伏せ',
    formCues: ['ベンチを45°にしてうつ伏せ、胸を預ける', '反動が使えないぶん軽めでOK', '引き切ったとき肩甲骨を1秒寄せ続ける'],
    commonMistake: '胸がベンチから浮く(反動を使っている)',
  },
  {
    name: 'ダンベルデッドリフト',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'legs', 'glutes'],
    movementType: 'compound',
    movementPattern: 'hinge',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 6,
    repRangeMax: 10,
    initialWeightFactor: 0.3,
    isActive: 1,
    formCues: ['ダンベルは体の真横、体に沿って上下', '背すじ一直線のまま股関節から曲げる', '立ち上がるとき尻を締める'],
    commonMistake: '腰を反らせて引き上げる(背中は常にニュートラル)',
  },
  {
    name: 'ダンベルプルオーバー',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'chest'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.15,
    isActive: 1,
    note: 'ダンベル1個を両手で保持',
    formCues: ['ダンベル1個を両手で頭上へ弧を描いて下ろす', '肘は軽く曲げたまま固定', '脇腹の伸びを感じる範囲まで'],
    commonMistake: '下ろしすぎて肩を痛める(無理のない可動域で)',
  },
  {
    name: 'ダンベルシュラッグ',
    primaryMuscle: 'back',
    muscleGroups: ['back'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: '僧帽筋狙い',
    formCues: ['肩を真上にすくめて1秒キープ', '腕は力を抜いてぶら下げたまま'],
    commonMistake: '肩を回す(真上→真下の直線でOK)',
  },
  {
    name: 'バックエクステンション',
    searchKeyword: 'スーパーマン 背筋 自重 やり方',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'glutes'],
    movementType: 'isolation',
    movementPattern: 'hinge',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 12,
    repRangeMax: 20,
    isActive: 1,
    note: '床でうつ伏せ(スーパーマン)。脊柱起立筋狙い',
    formCues: ['うつ伏せで手足を同時に浮かせて2秒キープ', '目線は床のまま(首を反らさない)'],
    commonMistake: '勢いで反動をつける(ゆっくり上げ下げ)',
  },
  // ===== 肩 =====
  {
    name: 'シーテッドショルダープレス',
    searchKeyword: 'ダンベルショルダープレス フォーム',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'vertical_press',
    emphasis: 'front',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.17,
    isActive: 1,
    formCues: ['ベンチを90°にして背中を預ける', '耳の横から真上へ、肘は伸ばし切る手前まで', '下ろすのは肘が90°になる高さまで'],
    commonMistake: '腰を反ってベンチから浮かせる(重すぎのサイン)',
  },
  {
    name: 'サイドレイズ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'side',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 12,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
    formCues: ['肘を軽く曲げ、小指側からやや前方に上げる', '肩の高さまでで十分', '下ろすとき3秒かけて耐える'],
    commonMistake: '反動と僧帽筋で持ち上げる(軽い重量で丁寧に)',
  },
  {
    name: 'リアデルトフライ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'back'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'rear',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 12,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
    note: '前傾姿勢。肩後部狙い',
    formCues: ['上体を前傾し、腕を真横に開く', '肩甲骨を寄せすぎない(肩後部で止める)'],
    commonMistake: '上体が起きて背中の種目になる',
  },
  {
    name: 'アップライトロウ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    movementType: 'compound',
    movementPattern: 'row',
    emphasis: 'side',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 12,
    initialWeightFactor: 0.14,
    isActive: 1,
    formCues: ['体の前面に沿って肘から引き上げる', '肘は肩の高さまで(それ以上は上げない)'],
    commonMistake: '手首を返して持ち上げる(肩を痛めやすい)',
  },
  {
    name: 'パイクプッシュアップ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'chest'],
    movementType: 'compound',
    movementPattern: 'vertical_press',
    emphasis: 'front',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
    formCues: ['尻を高く上げた「へ」の字姿勢', '頭を手の少し前の床に向かって下ろす', 'きつければ足を手に近づけて調整'],
    commonMistake: '普通の腕立てになっている(尻の高さをキープ)',
  },
  // ===== 腕 =====
  {
    name: 'ダンベルカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'biceps',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.11,
    isActive: 1,
    formCues: ['肘を体側に固定して前腕だけ動かす', '下ろすとき3秒かけて耐える'],
    commonMistake: '肘が前に出て肩で挙げる(反動NG)',
  },
  {
    name: 'ハンマーカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'biceps',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.11,
    isActive: 1,
    formCues: ['手のひら同士を向かい合わせたまま上げる', '肘は体側に固定'],
    commonMistake: '体を揺らして反動を使う',
  },
  {
    name: 'インクラインダンベルカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'biceps',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 45,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.09,
    isActive: 1,
    formCues: ['ベンチを45°にして腕を後ろに垂らす', 'ストレッチがかかるぶん軽めでOK'],
    commonMistake: '肩が前に出て伸ばしきれていない',
  },
  {
    name: 'ライイングトライセプスエクステンション',
    searchKeyword: 'ダンベル トライセプスエクステンション フォーム',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'triceps',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.09,
    isActive: 1,
    formCues: ['仰向けで肘を天井に向けて固定', '額の横へゆっくり下ろして押し戻す'],
    commonMistake: '肘が開いてプレスになる',
  },
  {
    name: 'オーバーヘッドトライセプスエクステンション',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'triceps',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.12,
    isActive: 1,
    note: 'ダンベル1個を両手で保持',
    formCues: ['ダンベル1個を両手で頭上に構える', '肘を耳の横に固定し、頭の後ろへ下ろす'],
    commonMistake: '肘が外に開く(二の腕に効かなくなる)',
  },
  {
    name: 'トライセプスキックバック',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    emphasis: 'triceps',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
    formCues: ['前傾して上腕を床と平行に固定', '肘から先だけを後ろに伸ばし切って1秒キープ'],
    commonMistake: '腕全体を振る(上腕は動かさない)',
  },
  {
    name: 'ベンチディップス',
    primaryMuscle: 'arms',
    muscleGroups: ['arms', 'chest', 'shoulders'],
    movementType: 'compound',
    movementPattern: 'vertical_press',
    emphasis: 'triceps',
    requiredEquipment: ['bodyweight', 'bench'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
    formCues: ['ベンチに手をつき、体はベンチに沿って垂直に下ろす', '肘が90°になったら押し上げる', 'きつければ膝を曲げて調整'],
    commonMistake: '体がベンチから離れて肩に負担がかかる',
  },
  // ===== 脚 =====
  {
    name: 'ゴブレットスクワット',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    movementPattern: 'squat',
    emphasis: 'quad',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: 'ダンベル1個を胸の前で保持',
    formCues: ['ダンベル1個を胸の前で縦に抱える', '肘が膝の内側に入る深さまでしゃがむ', 'かかと重心・胸を張ったまま'],
    commonMistake: '膝が内に入る(つま先と同じ向きをキープ)',
  },
  {
    name: 'ダンベルランジ',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    movementPattern: 'squat',
    emphasis: 'quad',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.2,
    isActive: 1,
    note: 'レップ数は片脚あたり',
    formCues: ['両手にダンベルを提げ、大きく一歩前へ', '後ろ膝を床すれすれまで下ろす', '前脚のかかとで押し戻る'],
    commonMistake: '歩幅が狭く膝がつま先より大きく前に出る',
  },
  {
    name: 'ブルガリアンスクワット',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    movementPattern: 'squat',
    emphasis: 'quad',
    requiredEquipment: ['dumbbell', 'bench'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.15,
    isActive: 1,
    note: '後ろ足をベンチに乗せる。レップ数は片脚あたり',
    formCues: ['後ろ足の甲をベンチに乗せる', '上体はやや前傾、前脚に体重を乗せて沈む', 'きつい種目なので軽めスタートでOK'],
    commonMistake: '前脚の歩幅が狭い(膝主導になり膝を痛める)',
  },
  {
    name: 'ルーマニアンデッドリフト',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes', 'back'],
    movementType: 'compound',
    movementPattern: 'hinge',
    emphasis: 'ham_glute',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.26,
    isActive: 1,
    note: 'ハムストリングス狙い',
    formCues: ['膝は軽く曲げたまま固定、尻を後ろに引く', 'もも裏の伸びを感じたら立ち上がる', 'ダンベルは太ももに沿わせて上下'],
    commonMistake: '膝を曲げてスクワットになる(股関節だけ動かす)',
  },
  {
    name: 'ダンベルカーフレイズ',
    primaryMuscle: 'legs',
    muscleGroups: ['legs'],
    movementType: 'isolation',
    movementPattern: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 15,
    repRangeMax: 20,
    initialWeightFactor: 0.26,
    isActive: 1,
    formCues: ['つま先立ちの一番高いところで1秒キープ', 'かかとをゆっくり下ろし切ってストレッチ'],
    commonMistake: '可動域が狭い(上も下も動かし切る)',
  },
  {
    name: '自重スクワット',
    searchKeyword: 'スクワット 正しいフォーム',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    movementPattern: 'squat',
    emphasis: 'quad',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 25,
    isActive: 1,
    formCues: ['足は肩幅、つま先はやや外向き', '太ももが床と平行になる深さまで', '腕を前に伸ばすとバランスが取りやすい'],
    commonMistake: '浅いしゃがみで回数だけ稼ぐ',
  },
  // ===== 尻 =====
  {
    name: 'ダンベルヒップスラスト',
    searchKeyword: 'ヒップスラスト ダンベル やり方',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'legs'],
    movementType: 'compound',
    movementPattern: 'hinge',
    requiredEquipment: ['dumbbell', 'bench'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: '背中をベンチに預け、ダンベル1個を腰に乗せる',
    formCues: ['肩甲骨をベンチに預け、ダンベルを腰骨に乗せる', '尻を締めながら腰を天井へ突き上げる', 'トップで体が一直線・あごは引く'],
    commonMistake: '腰を反って上げる(尻の力で押し上げる)',
  },
  {
    name: 'グルートブリッジ',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'legs'],
    movementType: 'compound',
    movementPattern: 'hinge',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 20,
    isActive: 1,
    formCues: ['仰向けで膝を立て、かかとで床を押して腰を上げる', 'トップで尻を1秒締め続ける'],
    commonMistake: '腰の反りで上げる(みぞおちから膝まで一直線まで)',
  },
  // ===== 腹 =====
  {
    name: 'クランチ',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    movementPattern: 'core',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 25,
    isActive: 1,
    formCues: ['みぞおちを支点に背中を丸めて起きる', '肩甲骨が浮けば十分(起き上がらなくてよい)', '息を吐き切りながら丸める'],
    commonMistake: '首を手で引っ張る(手は添えるだけ)',
  },
  {
    name: 'レッグレイズ',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    movementPattern: 'core',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 12,
    repRangeMax: 20,
    isActive: 1,
    formCues: ['仰向けで脚を揃えて90°まで上げる', '下ろすとき腰が床から浮かない高さで止める'],
    commonMistake: '腰が反って床から浮く(手を尻の下に敷くと楽)',
  },
  {
    name: 'ロシアンツイスト',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    movementPattern: 'core',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 20,
    repRangeMax: 30,
    initialWeightFactor: 0.08,
    isActive: 1,
    note: 'ダンベル1個を両手で保持。レップ数は左右合計',
    formCues: ['上体を45°後ろに倒しキープ', 'ダンベルではなく胸ごと左右にひねる'],
    commonMistake: '腕だけ振って体幹がひねれていない',
  },
]
