import type { Exercise } from '../db/types'

// 種目マスタ初期データ(要件§7: ダンベル+アジャスタブルベンチ+自重で35種目前後)
// initialWeightFactor: 初回提案重量 = 体重 × 係数(ダンベル1個あたり・保守的)
// benchAngleDeg: ベンチ必須種目の推奨角度。器具設定の角度範囲外なら候補から除外される
export const INITIAL_EXERCISES: Omit<Exercise, 'id'>[] = [
  // ===== 胸 =====
  {
    name: 'ダンベルベンチプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
  },
  {
    name: 'インクラインダンベルプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 30,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.18,
    isActive: 1,
    note: '胸上部狙い',
  },
  {
    name: 'デクラインダンベルプレス',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: -15,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
    note: '胸下部狙い',
  },
  {
    name: 'ダンベルフライ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.1,
    isActive: 1,
  },
  {
    name: 'インクラインダンベルフライ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 30,
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.09,
    isActive: 1,
  },
  {
    name: 'プッシュアップ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 10,
    repRangeMax: 20,
    isActive: 1,
  },
  {
    name: 'デクラインプッシュアップ',
    primaryMuscle: 'chest',
    muscleGroups: ['chest', 'shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight', 'bench'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
    note: '足をベンチに乗せる。胸上部狙い',
  },
  // ===== 背中 =====
  {
    name: 'ワンハンドダンベルロウ',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.28,
    isActive: 1,
    note: '片手・片膝をベンチに置く',
  },
  {
    name: 'ベントオーバーダンベルロウ',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.22,
    isActive: 1,
  },
  {
    name: 'チェストサポーテッドロウ',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 45,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.18,
    isActive: 1,
    note: 'インクラインベンチにうつ伏せ',
  },
  {
    name: 'ダンベルデッドリフト',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'legs', 'glutes'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 6,
    repRangeMax: 10,
    initialWeightFactor: 0.3,
    isActive: 1,
  },
  {
    name: 'ダンベルプルオーバー',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'chest'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.15,
    isActive: 1,
    note: 'ダンベル1個を両手で保持',
  },
  {
    name: 'ダンベルシュラッグ',
    primaryMuscle: 'back',
    muscleGroups: ['back'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: '僧帽筋狙い',
  },
  {
    name: 'バックエクステンション',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'glutes'],
    movementType: 'isolation',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 12,
    repRangeMax: 20,
    isActive: 1,
    note: '床でうつ伏せ(スーパーマン)。脊柱起立筋狙い',
  },
  // ===== 肩 =====
  {
    name: 'シーテッドショルダープレス',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    initialWeightFactor: 0.17,
    isActive: 1,
  },
  {
    name: 'サイドレイズ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 12,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
  },
  {
    name: 'リアデルトフライ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'back'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 12,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
    note: '前傾姿勢。肩後部狙い',
  },
  {
    name: 'アップライトロウ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 12,
    initialWeightFactor: 0.14,
    isActive: 1,
  },
  {
    name: 'パイクプッシュアップ',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'chest'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
  },
  // ===== 腕 =====
  {
    name: 'ダンベルカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.11,
    isActive: 1,
  },
  {
    name: 'ハンマーカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.11,
    isActive: 1,
  },
  {
    name: 'インクラインダンベルカール',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 45,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.09,
    isActive: 1,
  },
  {
    name: 'ライイングトライセプスエクステンション',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell', 'bench'],
    benchAngleDeg: 0,
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.09,
    isActive: 1,
  },
  {
    name: 'オーバーヘッドトライセプスエクステンション',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.12,
    isActive: 1,
    note: 'ダンベル1個を両手で保持',
  },
  {
    name: 'トライセプスキックバック',
    primaryMuscle: 'arms',
    muscleGroups: ['arms'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.07,
    isActive: 1,
  },
  {
    name: 'ベンチディップス',
    primaryMuscle: 'arms',
    muscleGroups: ['arms', 'chest', 'shoulders'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight', 'bench'],
    repRangeMin: 8,
    repRangeMax: 15,
    isActive: 1,
  },
  // ===== 脚 =====
  {
    name: 'ゴブレットスクワット',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: 'ダンベル1個を胸の前で保持',
  },
  {
    name: 'ダンベルランジ',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.2,
    isActive: 1,
    note: 'レップ数は片脚あたり',
  },
  {
    name: 'ブルガリアンスクワット',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.15,
    isActive: 1,
    note: '後ろ足をベンチに乗せる。レップ数は片脚あたり',
  },
  {
    name: 'ルーマニアンデッドリフト',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes', 'back'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 8,
    repRangeMax: 12,
    initialWeightFactor: 0.26,
    isActive: 1,
    note: 'ハムストリングス狙い',
  },
  {
    name: 'ダンベルカーフレイズ',
    primaryMuscle: 'legs',
    muscleGroups: ['legs'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 15,
    repRangeMax: 20,
    initialWeightFactor: 0.26,
    isActive: 1,
  },
  {
    name: '自重スクワット',
    primaryMuscle: 'legs',
    muscleGroups: ['legs', 'glutes'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 25,
    isActive: 1,
  },
  // ===== 尻 =====
  {
    name: 'ダンベルヒップスラスト',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'legs'],
    movementType: 'compound',
    requiredEquipment: ['dumbbell', 'bench'],
    repRangeMin: 10,
    repRangeMax: 15,
    initialWeightFactor: 0.3,
    isActive: 1,
    note: '背中をベンチに預け、ダンベル1個を腰に乗せる',
  },
  {
    name: 'グルートブリッジ',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'legs'],
    movementType: 'compound',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 20,
    isActive: 1,
  },
  // ===== 腹 =====
  {
    name: 'クランチ',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 15,
    repRangeMax: 25,
    isActive: 1,
  },
  {
    name: 'レッグレイズ',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    requiredEquipment: ['bodyweight'],
    repRangeMin: 12,
    repRangeMax: 20,
    isActive: 1,
  },
  {
    name: 'ロシアンツイスト',
    primaryMuscle: 'abs',
    muscleGroups: ['abs'],
    movementType: 'isolation',
    requiredEquipment: ['dumbbell'],
    repRangeMin: 20,
    repRangeMax: 30,
    initialWeightFactor: 0.08,
    isActive: 1,
    note: 'ダンベル1個を両手で保持。レップ数は左右合計',
  },
]
